# Vlad
**99516558**


# Gappasov
**991516558**

int

In [ ]:
<class 'int'>

# Functions 

In [13]:
list_values = [1,2,3]
set_values = (1,2,3)

print(id(list_values))
print(id(set_values))

4356439936
4357052160


In [16]:
list_values +=[4,5,6]
set_values +=(4,5,6)
print(id(list_values))
print(id(set_values))

4356439936
4376394944


In [17]:
def add_numbers(x,y,):
    return x+y

In [18]:
add_numbers(1,2)

3

In [21]:
def add_num(x,y,z=None):
    if z == None:
        return x+y
    else:
        return x+y+z

In [22]:
print(add_num(1,2))
print(add_num(1,2,3))

3
6


# Lamdba

In [23]:
my_function= lambda a,b,c:a+b

In [25]:
my_function (1,2,3)

3

# Random List


In [29]:
# The time it takes to run something


In [30]:
%%time
import random
random_list=[]
for i in range(1000):
    random_list.append(random.randint(0,100))

print(random_list)


[63, 81, 30, 99, 20, 93, 91, 2, 41, 73, 74, 45, 47, 20, 83, 93, 33, 72, 59, 27, 64, 50, 69, 22, 61, 91, 75, 73, 40, 67, 45, 92, 68, 28, 49, 62, 17, 79, 90, 51, 3, 100, 31, 12, 46, 90, 51, 56, 63, 18, 87, 6, 25, 16, 67, 10, 25, 33, 45, 88, 44, 51, 95, 83, 61, 17, 34, 63, 93, 3, 27, 89, 73, 68, 43, 58, 68, 66, 2, 72, 98, 50, 95, 77, 12, 14, 10, 0, 65, 40, 42, 52, 26, 40, 43, 62, 64, 55, 81, 11, 45, 44, 73, 82, 65, 94, 89, 51, 30, 72, 37, 46, 34, 27, 15, 82, 1, 91, 23, 40, 72, 31, 64, 30, 80, 56, 1, 52, 64, 3, 100, 78, 64, 48, 85, 6, 32, 67, 52, 75, 9, 62, 10, 72, 61, 25, 74, 97, 79, 64, 14, 9, 12, 37, 20, 24, 81, 8, 43, 6, 50, 90, 77, 58, 17, 82, 15, 2, 3, 27, 82, 13, 75, 45, 48, 100, 29, 54, 94, 82, 24, 95, 64, 56, 16, 10, 5, 42, 25, 41, 40, 6, 68, 37, 20, 31, 6, 32, 88, 78, 41, 99, 81, 91, 48, 1, 38, 61, 69, 53, 56, 85, 77, 60, 47, 54, 59, 65, 20, 100, 82, 68, 67, 11, 20, 55, 38, 26, 74, 21, 50, 40, 62, 8, 26, 22, 2, 85, 35, 24, 41, 94, 31, 48, 95, 40, 17, 24, 54, 57, 39, 99, 16, 95, 4

# To Iterate over a list


In [32]:
for i in random_list:
    print(i)

63
81
30
99
20
93
91
2
41
73
74
45
47
20
83
93
33
72
59
27
64
50
69
22
61
91
75
73
40
67
45
92
68
28
49
62
17
79
90
51
3
100
31
12
46
90
51
56
63
18
87
6
25
16
67
10
25
33
45
88
44
51
95
83
61
17
34
63
93
3
27
89
73
68
43
58
68
66
2
72
98
50
95
77
12
14
10
0
65
40
42
52
26
40
43
62
64
55
81
11
45
44
73
82
65
94
89
51
30
72
37
46
34
27
15
82
1
91
23
40
72
31
64
30
80
56
1
52
64
3
100
78
64
48
85
6
32
67
52
75
9
62
10
72
61
25
74
97
79
64
14
9
12
37
20
24
81
8
43
6
50
90
77
58
17
82
15
2
3
27
82
13
75
45
48
100
29
54
94
82
24
95
64
56
16
10
5
42
25
41
40
6
68
37
20
31
6
32
88
78
41
99
81
91
48
1
38
61
69
53
56
85
77
60
47
54
59
65
20
100
82
68
67
11
20
55
38
26
74
21
50
40
62
8
26
22
2
85
35
24
41
94
31
48
95
40
17
24
54
57
39
99
16
95
46
95
94
3
29
12
0
86
93
62
0
66
11
63
90
53
86
81
7
94
43
68
78
42
47
56
96
69
8
73
24
45
15
10
15
72
54
44
98
7
95
49
8
80
12
56
6
97
6
95
21
65
1
40
28
22
62
91
73
80
48
13
11
40
94
94
21
21
17
96
81
35
65
84
64
12
32
63
65
20
41
57
90
86
10
57
16
71
97

In [33]:
# Another way to iterate over a list is to iterate over an index


for i in range(len(random_list)):
    print(random_list[i])

# To check if an element is in the list or not, and it is supposed to return true or false

In [36]:
if 65 in random_list:
    print("True")

True


In [37]:
# Select parts of a list, based on the index. For e.x., index 7 to index 17. Go from index 6 - index 16.

In [38]:
random_list[6:16]

[91, 2, 41, 73, 74, 45, 47, 20, 83, 93]

In [ ]:
# To find the last 10 elements

In [39]:
random_list[-10:]

[92, 12, 44, 64, 70, 72, 33, 43, 77, 68]

In [40]:
random_list[6:16:2]

[91, 41, 74, 47, 83]

# Num Py Arrays

In [42]:
import numpy as np

In [43]:
#Work with arrays#

In [44]:
#Convert a list to an array

In [45]:
mylist=[1,2,3]
x = np.array(mylist)

In [46]:
x

array([1, 2, 3])

In [48]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [49]:
#Create a list of lists and create an array from that. It will be rows and columns

In [52]:
m=np.array([[7,8,9],[10,11,12]])

In [53]:
m.shape

(2, 3)

In [54]:
#Create an array with evenly-spaced values

In [57]:
n= np.arange(0,30,2)

In [59]:
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [60]:
#Reshape an array

In [61]:
n.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [62]:
#To fill an array with elements, use lin.space to put in evenly-space values

In [63]:
a =np.linspace(0,4,9)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
#To put the array into a 3x3 array

In [66]:
a.resize(3,3)
a

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

# Special types of arrays

In [68]:
#Use special functions to create special types of arrays#

In [69]:
#Create an array of all 1's, but you must specify dimensions

In [70]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [71]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
#Diagonal matrix. This means that everything has to be 0, except for elements in the diagonal.

In [76]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [77]:
#Create an array using repeating list#

In [79]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [80]:
#Create an array using a repeat function, that will repeat the function a x amount of times.

In [81]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

# Combining Arrays

In [83]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [84]:
# Stack an array in a sequence vertically#

In [85]:
np.vstack([p, 2 * p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [86]:
# Stack an array in a sequence horizontally#

In [87]:
np.hstack([p, 2 * p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [88]:
# Number OPerations using Arrays

In [89]:
print(x + y)
print(x - y)

[5 7 9]
[-3 -3 -3]


In [90]:
print(x * y)
print(x / y)

[ 4 10 18]
[0.25 0.4  0.5 ]


In [91]:
print(x **2)

[1 4 9]


In [92]:
# Dot Product# 

In [93]:
x.dot(y)

32

In [94]:
z = np.array([y, y**2])


In [95]:
z.shape

(2, 3)

In [96]:
z


array([[ 4,  5,  6],
       [16, 25, 36]])

In [97]:
#Get the transpose

In [98]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [99]:
z.shape

(2, 3)

In [100]:
#Use data type to get the data type of elements in the array

In [101]:
z.dtype


dtype('int64')

In [102]:
#Use astype to cast a specific type

In [104]:
z = z.astype("f")
z.dtype


dtype('float32')

# Math Functions

In [106]:
a = np.array([-4, -2, 1, 3, 5])

In [107]:
a.sum()

3

In [108]:
a.max()


5

In [109]:
a.min()

-4

In [110]:
#argmax and argmin will return the index of the maximum and minimum values in the array#

In [111]:
a.argmax()

4

In [112]:
a.argmin()

0

In [113]:
a.min()

-4

In [114]:
a.std()

3.2619012860600183

# Array Indexing/Slicing

In [116]:
s = np.arange(13) **2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [117]:
#Use bracket notation to get the value at a specific index. Remember, that the index begins at 0#

In [119]:
s[0], s[4], s[-1]

(0, 16, 144)

In [120]:
#Use : to indicate a range.

In [121]:
s[1:5]

array([ 1,  4,  9, 16])

In [122]:
#Use a negative to be able to count from the back.

In [123]:
s[-4:]

array([ 81, 100, 121, 144])

In [124]:
# A second : can be used to indicate step-size.

In [125]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [126]:
#A multidimensional array#

In [127]:
r = np.arange(36)
r.resize((6,6))
r


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [128]:
# Use bracket notation to slice: row, column

In [129]:
r[2, 2]

14

In [130]:
#And use :  to select a range of rows and columns

In [131]:
r[3, 3:6]

array([21, 22, 23])

In [132]:
#Select all rows up to and not including row 2, and all the columns up to and not including, the last row#


In [133]:
r[:-2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [134]:
#Slice the last row, and only every other element#

In [135]:
r[-1, ::2]

array([30, 32, 34])

In [136]:
#We can also do conditional indexing. Select the values from the array that are > 30#

In [137]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [138]:
#Assign all values in the array that are > 30 to the value 30#

In [139]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [140]:
test=np.random.randint(0,10,(4,3))
test

array([[7, 0, 0],
       [7, 9, 1],
       [5, 7, 8],
       [7, 8, 1]])

In [142]:
for i in range(len(test)):
    print(test[i])

[7 0 0]
[7 9 1]
[5 7 8]
[7 8 1]


In [144]:
for i, row in enumerate (test):
    print("row", i,"is",row)

row 0 is [7 0 0]
row 1 is [7 9 1]
row 2 is [5 7 8]
row 3 is [7 8 1]


In [145]:
test2=test**2
test2

array([[49,  0,  0],
       [49, 81,  1],
       [25, 49, 64],
       [49, 64,  1]])

In [150]:
for i, j, in zip(test, test2)
    print(i,"+",j,"=",i+j)

SyntaxError: expected ':' (1934811981.py, line 1)